version: "3.8"

services: 
    postgres:
        image: postgres:13.1-alpine
        container_name: database
        restart: always
        ports: 
            - "5432:5432"
        volumes: 
            - ./shopper.sql:/data/dump.sql
            - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
    api:
        build: 
            context: ./api
            dockerfile: ./Dockerfile
        container_name: api
        restart: always
        ports: 
            - "5000:5000"
        environment: 
            - POSTGRES_URL=postgresql://postgres:1234@postgres:5432/postgres
        depends_on: 
            - postgres